"""update db

Revision ID: 8f7d41994a20
Revises: f74296dfc600
Create Date: 2024-05-09 15:18:34.773181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7d41994a20'
down_revision = 'f74296dfc600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('movie_id', sa.Integer(), nullable=True))
    op.alter_column('actors', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.create_foreign_key(None, 'actors', 'movies', ['movie_id'], ['id'])
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_constraint(None, 'actors', type_='foreignkey')
    op.alter_column('actors', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('actors', 'movie_id')
    # ### end Alembic commands ###
