"""Initial migration

Revision ID: f74296dfc600
Revises: 
Create Date: 2024-05-09 10:43:43.064381

"""
from datetime import date
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74296dfc600'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not op.get_bind().dialect.has_table(op.get_bind(), "actors"):
        op.create_table(
            'actors',
            sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column('name', sa.String(120), nullable=False),
            sa.Column('gender', sa.String(50), nullable=True),
            sa.Column('age', sa.Integer(), nullable=True),
        )

    if not op.get_bind().dialect.has_table(op.get_bind(), "movies"):
        op.create_table(
            'movies',
            sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column('title', sa.String(120), nullable=False),
            sa.Column('release_date', sa.Date(), nullable=True),
        )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    op.drop_table('actors')
    # ### end Alembic commands ###
